/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.records;


import com.kenvix.studentmanager.orm.tables.Papers;
import com.kenvix.studentmanager.orm.tables.interfaces.IPapers;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PapersRecord extends UpdatableRecordImpl<PapersRecord> implements Record3<Long, Long, String>, IPapers {

    private static final long serialVersionUID = 1301016225;

    /**
     * Setter for <code>papers.id</code>.
     */
    @Override
    public PapersRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>papers.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>papers.person_id</code>.
     */
    @Override
    public PapersRecord setPersonId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>papers.person_id</code>.
     */
    @Override
    public Long getPersonId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>papers.title</code>.
     */
    @Override
    public PapersRecord setTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>papers.title</code>.
     */
    @Override
    public String getTitle() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Papers.PAPERS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Papers.PAPERS.PERSON_ID;
    }

    @Override
    public Field<String> field3() {
        return Papers.PAPERS.TITLE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getPersonId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getPersonId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public PapersRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PapersRecord value2(Long value) {
        setPersonId(value);
        return this;
    }

    @Override
    public PapersRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public PapersRecord values(Long value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IPapers from) {
        setId(from.getId());
        setPersonId(from.getPersonId());
        setTitle(from.getTitle());
    }

    @Override
    public <E extends IPapers> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PapersRecord
     */
    public PapersRecord() {
        super(Papers.PAPERS);
    }

    /**
     * Create a detached, initialised PapersRecord
     */
    public PapersRecord(Long id, Long personId, String title) {
        super(Papers.PAPERS);

        set(0, id);
        set(1, personId);
        set(2, title);
    }
}
