/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.records;


import com.kenvix.studentmanager.orm.tables.PeopleStudent;
import com.kenvix.studentmanager.orm.tables.interfaces.IPeopleStudent;

import javax.annotation.processing.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * View 'student_manager.people_student' references invalid table(s) or column(s) 
 * or function(s) or definer/invoker of view lack rights to use them
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PeopleStudentRecord extends TableRecordImpl<PeopleStudentRecord> implements IPeopleStudent {

    private static final long serialVersionUID = 827953642;

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IPeopleStudent from) {
    }

    @Override
    public <E extends IPeopleStudent> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PeopleStudentRecord
     */
    public PeopleStudentRecord() {
        super(PeopleStudent.PEOPLE_STUDENT);
    }
}
