/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.records;


import com.kenvix.studentmanager.orm.tables.StudentClassMap;
import com.kenvix.studentmanager.orm.tables.interfaces.IStudentClassMap;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * View 'student_manager.people_student' references invalid table(s) or column(s) 
 * or function(s) or definer/invoker of view lack rights to use them
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentClassMapRecord extends UpdatableRecordImpl<StudentClassMapRecord> implements Record3<Long, Long, Long>, IStudentClassMap {

    private static final long serialVersionUID = 38887582;

    /**
     * Setter for <code>student_class_map.id</code>.
     */
    @Override
    public StudentClassMapRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>student_class_map.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>student_class_map.student_id</code>.
     */
    @Override
    public StudentClassMapRecord setStudentId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>student_class_map.student_id</code>.
     */
    @Override
    public Long getStudentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>student_class_map.class_id</code>.
     */
    @Override
    public StudentClassMapRecord setClassId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>student_class_map.class_id</code>.
     */
    @Override
    public Long getClassId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return StudentClassMap.STUDENT_CLASS_MAP.ID;
    }

    @Override
    public Field<Long> field2() {
        return StudentClassMap.STUDENT_CLASS_MAP.STUDENT_ID;
    }

    @Override
    public Field<Long> field3() {
        return StudentClassMap.STUDENT_CLASS_MAP.CLASS_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getStudentId();
    }

    @Override
    public Long component3() {
        return getClassId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getStudentId();
    }

    @Override
    public Long value3() {
        return getClassId();
    }

    @Override
    public StudentClassMapRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public StudentClassMapRecord value2(Long value) {
        setStudentId(value);
        return this;
    }

    @Override
    public StudentClassMapRecord value3(Long value) {
        setClassId(value);
        return this;
    }

    @Override
    public StudentClassMapRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IStudentClassMap from) {
        setId(from.getId());
        setStudentId(from.getStudentId());
        setClassId(from.getClassId());
    }

    @Override
    public <E extends IStudentClassMap> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentClassMapRecord
     */
    public StudentClassMapRecord() {
        super(StudentClassMap.STUDENT_CLASS_MAP);
    }

    /**
     * Create a detached, initialised StudentClassMapRecord
     */
    public StudentClassMapRecord(Long id, Long studentId, Long classId) {
        super(StudentClassMap.STUDENT_CLASS_MAP);

        set(0, id);
        set(1, studentId);
        set(2, classId);
    }
}
