/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.interfaces;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IClasses extends Serializable {

    /**
     * Setter for <code>classes.id</code>.
     */
    public IClasses setId(Long value);

    /**
     * Getter for <code>classes.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>classes.master_id</code>.
     */
    public IClasses setMasterId(Long value);

    /**
     * Getter for <code>classes.master_id</code>.
     */
    public Long getMasterId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IClasses
     */
    public void from(IClasses from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IClasses
     */
    public <E extends IClasses> E into(E into);
}
