/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.interfaces;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IClassCourseMap extends Serializable {

    /**
     * Setter for <code>class_course_map.id</code>.
     */
    public IClassCourseMap setId(Long value);

    /**
     * Getter for <code>class_course_map.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>class_course_map.class_id</code>.
     */
    public IClassCourseMap setClassId(Long value);

    /**
     * Getter for <code>class_course_map.class_id</code>.
     */
    public Long getClassId();

    /**
     * Setter for <code>class_course_map.course_id</code>.
     */
    public IClassCourseMap setCourseId(Long value);

    /**
     * Getter for <code>class_course_map.course_id</code>.
     */
    public Long getCourseId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IClassCourseMap
     */
    public void from(IClassCourseMap from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IClassCourseMap
     */
    public <E extends IClassCourseMap> E into(E into);
}
