/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.interfaces;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICourses extends Serializable {

    /**
     * Setter for <code>courses.id</code>.
     */
    public ICourses setId(Long value);

    /**
     * Getter for <code>courses.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>courses.name</code>.
     */
    public ICourses setName(String value);

    /**
     * Getter for <code>courses.name</code>.
     */
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICourses
     */
    public void from(ICourses from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICourses
     */
    public <E extends ICourses> E into(E into);
}
