/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.interfaces;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPapers extends Serializable {

    /**
     * Setter for <code>papers.id</code>.
     */
    public IPapers setId(Long value);

    /**
     * Getter for <code>papers.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>papers.person_id</code>.
     */
    public IPapers setPersonId(Long value);

    /**
     * Getter for <code>papers.person_id</code>.
     */
    public Long getPersonId();

    /**
     * Setter for <code>papers.title</code>.
     */
    public IPapers setTitle(String value);

    /**
     * Getter for <code>papers.title</code>.
     */
    public String getTitle();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IPapers
     */
    public void from(IPapers from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IPapers
     */
    public <E extends IPapers> E into(E into);
}
