/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.interfaces;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * View 'student_manager.people_student' references invalid table(s) or column(s) 
 * or function(s) or definer/invoker of view lack rights to use them
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPeopleStudent extends Serializable {

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IPeopleStudent
     */
    public void from(IPeopleStudent from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IPeopleStudent
     */
    public <E extends IPeopleStudent> E into(E into);
}
