/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.interfaces;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * View 'student_manager.people_student' references invalid table(s) or column(s) 
 * or function(s) or definer/invoker of view lack rights to use them
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IStudentClassMap extends Serializable {

    /**
     * Setter for <code>student_class_map.id</code>.
     */
    public IStudentClassMap setId(Long value);

    /**
     * Getter for <code>student_class_map.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>student_class_map.student_id</code>.
     */
    public IStudentClassMap setStudentId(Long value);

    /**
     * Getter for <code>student_class_map.student_id</code>.
     */
    public Long getStudentId();

    /**
     * Setter for <code>student_class_map.class_id</code>.
     */
    public IStudentClassMap setClassId(Long value);

    /**
     * Getter for <code>student_class_map.class_id</code>.
     */
    public Long getClassId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IStudentClassMap
     */
    public void from(IStudentClassMap from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IStudentClassMap
     */
    public <E extends IStudentClassMap> E into(E into);
}
