/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.interfaces;


import com.kenvix.studentmanager.orm.enums.StudentsStatus;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * View 'student_manager.people_student' references invalid table(s) or column(s) 
 * or function(s) or definer/invoker of view lack rights to use them
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IStudents extends Serializable {

    /**
     * Setter for <code>students.person_id</code>.
     */
    public IStudents setPersonId(Long value);

    /**
     * Getter for <code>students.person_id</code>.
     */
    public Long getPersonId();

    /**
     * Setter for <code>students.is_graduable</code>.
     */
    public IStudents setIsGraduable(Byte value);

    /**
     * Getter for <code>students.is_graduable</code>.
     */
    public Byte getIsGraduable();

    /**
     * Setter for <code>students.status</code>.
     */
    public IStudents setStatus(StudentsStatus value);

    /**
     * Getter for <code>students.status</code>.
     */
    public StudentsStatus getStatus();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IStudents
     */
    public void from(IStudents from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IStudents
     */
    public <E extends IStudents> E into(E into);
}
