/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.pojos;


import com.kenvix.studentmanager.orm.tables.interfaces.IClasses;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Classes implements IClasses {

    private static final long serialVersionUID = 1173917257;

    private Long id;
    private Long masterId;

    public Classes() {}

    public Classes(IClasses value) {
        this.id = value.getId();
        this.masterId = value.getMasterId();
    }

    public Classes(
        Long id,
        Long masterId
    ) {
        this.id = id;
        this.masterId = masterId;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public Classes setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public Long getMasterId() {
        return this.masterId;
    }

    @Override
    public Classes setMasterId(Long masterId) {
        this.masterId = masterId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Classes (");

        sb.append(id);
        sb.append(", ").append(masterId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IClasses from) {
        setId(from.getId());
        setMasterId(from.getMasterId());
    }

    @Override
    public <E extends IClasses> E into(E into) {
        into.from(this);
        return into;
    }
}
