/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.pojos;


import com.kenvix.studentmanager.orm.tables.interfaces.IPapers;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Papers implements IPapers {

    private static final long serialVersionUID = -1959227646;

    private Long   id;
    private Long   personId;
    private String title;

    public Papers() {}

    public Papers(IPapers value) {
        this.id = value.getId();
        this.personId = value.getPersonId();
        this.title = value.getTitle();
    }

    public Papers(
        Long   id,
        Long   personId,
        String title
    ) {
        this.id = id;
        this.personId = personId;
        this.title = title;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public Papers setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public Long getPersonId() {
        return this.personId;
    }

    @Override
    public Papers setPersonId(Long personId) {
        this.personId = personId;
        return this;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public Papers setTitle(String title) {
        this.title = title;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Papers (");

        sb.append(id);
        sb.append(", ").append(personId);
        sb.append(", ").append(title);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IPapers from) {
        setId(from.getId());
        setPersonId(from.getPersonId());
        setTitle(from.getTitle());
    }

    @Override
    public <E extends IPapers> E into(E into) {
        into.from(this);
        return into;
    }
}
