/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.pojos;


import com.kenvix.studentmanager.orm.tables.interfaces.IPeopleStudent;

import javax.annotation.processing.Generated;


/**
 * View 'student_manager.people_student' references invalid table(s) or column(s) 
 * or function(s) or definer/invoker of view lack rights to use them
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PeopleStudent implements IPeopleStudent {

    private static final long serialVersionUID = 1697515932;


    public PeopleStudent() {}

    public PeopleStudent(IPeopleStudent value) {
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PeopleStudent (");


        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IPeopleStudent from) {
    }

    @Override
    public <E extends IPeopleStudent> E into(E into) {
        into.from(this);
        return into;
    }
}
