/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.pojos;


import com.kenvix.studentmanager.orm.tables.interfaces.IStudentClassMap;

import javax.annotation.processing.Generated;


/**
 * View 'student_manager.people_student' references invalid table(s) or column(s) 
 * or function(s) or definer/invoker of view lack rights to use them
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentClassMap implements IStudentClassMap {

    private static final long serialVersionUID = -981857557;

    private Long id;
    private Long studentId;
    private Long classId;

    public StudentClassMap() {}

    public StudentClassMap(IStudentClassMap value) {
        this.id = value.getId();
        this.studentId = value.getStudentId();
        this.classId = value.getClassId();
    }

    public StudentClassMap(
        Long id,
        Long studentId,
        Long classId
    ) {
        this.id = id;
        this.studentId = studentId;
        this.classId = classId;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public StudentClassMap setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public Long getStudentId() {
        return this.studentId;
    }

    @Override
    public StudentClassMap setStudentId(Long studentId) {
        this.studentId = studentId;
        return this;
    }

    @Override
    public Long getClassId() {
        return this.classId;
    }

    @Override
    public StudentClassMap setClassId(Long classId) {
        this.classId = classId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StudentClassMap (");

        sb.append(id);
        sb.append(", ").append(studentId);
        sb.append(", ").append(classId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IStudentClassMap from) {
        setId(from.getId());
        setStudentId(from.getStudentId());
        setClassId(from.getClassId());
    }

    @Override
    public <E extends IStudentClassMap> E into(E into) {
        into.from(this);
        return into;
    }
}
