/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.pojos;


import com.kenvix.studentmanager.orm.enums.StudentsStatus;
import com.kenvix.studentmanager.orm.tables.interfaces.IStudents;

import javax.annotation.processing.Generated;


/**
 * View 'student_manager.people_student' references invalid table(s) or column(s) 
 * or function(s) or definer/invoker of view lack rights to use them
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Students implements IStudents {

    private static final long serialVersionUID = 812269725;

    private Long           personId;
    private Byte           isGraduable;
    private StudentsStatus status;

    public Students() {}

    public Students(IStudents value) {
        this.personId = value.getPersonId();
        this.isGraduable = value.getIsGraduable();
        this.status = value.getStatus();
    }

    public Students(
        Long           personId,
        Byte           isGraduable,
        StudentsStatus status
    ) {
        this.personId = personId;
        this.isGraduable = isGraduable;
        this.status = status;
    }

    @Override
    public Long getPersonId() {
        return this.personId;
    }

    @Override
    public Students setPersonId(Long personId) {
        this.personId = personId;
        return this;
    }

    @Override
    public Byte getIsGraduable() {
        return this.isGraduable;
    }

    @Override
    public Students setIsGraduable(Byte isGraduable) {
        this.isGraduable = isGraduable;
        return this;
    }

    @Override
    public StudentsStatus getStatus() {
        return this.status;
    }

    @Override
    public Students setStatus(StudentsStatus status) {
        this.status = status;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Students (");

        sb.append(personId);
        sb.append(", ").append(isGraduable);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IStudents from) {
        setPersonId(from.getPersonId());
        setIsGraduable(from.getIsGraduable());
        setStatus(from.getStatus());
    }

    @Override
    public <E extends IStudents> E into(E into) {
        into.from(this);
        return into;
    }
}
