/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.daos;


import com.kenvix.studentmanager.orm.tables.Classes;
import com.kenvix.studentmanager.orm.tables.records.ClassesRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassesDao extends DAOImpl<ClassesRecord, com.kenvix.studentmanager.orm.tables.pojos.Classes, Long> {

    /**
     * Create a new ClassesDao without any configuration
     */
    public ClassesDao() {
        super(Classes.CLASSES, com.kenvix.studentmanager.orm.tables.pojos.Classes.class);
    }

    /**
     * Create a new ClassesDao with an attached configuration
     */
    public ClassesDao(Configuration configuration) {
        super(Classes.CLASSES, com.kenvix.studentmanager.orm.tables.pojos.Classes.class, configuration);
    }

    @Override
    public Long getId(com.kenvix.studentmanager.orm.tables.pojos.Classes object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Classes> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Classes.CLASSES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Classes> fetchById(Long... values) {
        return fetch(Classes.CLASSES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kenvix.studentmanager.orm.tables.pojos.Classes fetchOneById(Long value) {
        return fetchOne(Classes.CLASSES.ID, value);
    }

    /**
     * Fetch records that have <code>master_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Classes> fetchRangeOfMasterId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Classes.CLASSES.MASTER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>master_id IN (values)</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Classes> fetchByMasterId(Long... values) {
        return fetch(Classes.CLASSES.MASTER_ID, values);
    }
}
