/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.daos;


import com.kenvix.studentmanager.orm.tables.ClassCourseMap;
import com.kenvix.studentmanager.orm.tables.records.ClassCourseMapRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassCourseMapDao extends DAOImpl<ClassCourseMapRecord, com.kenvix.studentmanager.orm.tables.pojos.ClassCourseMap, Long> {

    /**
     * Create a new ClassCourseMapDao without any configuration
     */
    public ClassCourseMapDao() {
        super(ClassCourseMap.CLASS_COURSE_MAP, com.kenvix.studentmanager.orm.tables.pojos.ClassCourseMap.class);
    }

    /**
     * Create a new ClassCourseMapDao with an attached configuration
     */
    public ClassCourseMapDao(Configuration configuration) {
        super(ClassCourseMap.CLASS_COURSE_MAP, com.kenvix.studentmanager.orm.tables.pojos.ClassCourseMap.class, configuration);
    }

    @Override
    public Long getId(com.kenvix.studentmanager.orm.tables.pojos.ClassCourseMap object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.ClassCourseMap> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ClassCourseMap.CLASS_COURSE_MAP.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.ClassCourseMap> fetchById(Long... values) {
        return fetch(ClassCourseMap.CLASS_COURSE_MAP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kenvix.studentmanager.orm.tables.pojos.ClassCourseMap fetchOneById(Long value) {
        return fetchOne(ClassCourseMap.CLASS_COURSE_MAP.ID, value);
    }

    /**
     * Fetch records that have <code>class_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.ClassCourseMap> fetchRangeOfClassId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ClassCourseMap.CLASS_COURSE_MAP.CLASS_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>class_id IN (values)</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.ClassCourseMap> fetchByClassId(Long... values) {
        return fetch(ClassCourseMap.CLASS_COURSE_MAP.CLASS_ID, values);
    }

    /**
     * Fetch records that have <code>course_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.ClassCourseMap> fetchRangeOfCourseId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ClassCourseMap.CLASS_COURSE_MAP.COURSE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>course_id IN (values)</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.ClassCourseMap> fetchByCourseId(Long... values) {
        return fetch(ClassCourseMap.CLASS_COURSE_MAP.COURSE_ID, values);
    }
}
