/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.daos;


import com.kenvix.studentmanager.orm.tables.Courses;
import com.kenvix.studentmanager.orm.tables.records.CoursesRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoursesDao extends DAOImpl<CoursesRecord, com.kenvix.studentmanager.orm.tables.pojos.Courses, Long> {

    /**
     * Create a new CoursesDao without any configuration
     */
    public CoursesDao() {
        super(Courses.COURSES, com.kenvix.studentmanager.orm.tables.pojos.Courses.class);
    }

    /**
     * Create a new CoursesDao with an attached configuration
     */
    public CoursesDao(Configuration configuration) {
        super(Courses.COURSES, com.kenvix.studentmanager.orm.tables.pojos.Courses.class, configuration);
    }

    @Override
    public Long getId(com.kenvix.studentmanager.orm.tables.pojos.Courses object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Courses> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Courses.COURSES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Courses> fetchById(Long... values) {
        return fetch(Courses.COURSES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kenvix.studentmanager.orm.tables.pojos.Courses fetchOneById(Long value) {
        return fetchOne(Courses.COURSES.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Courses> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Courses.COURSES.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Courses> fetchByName(String... values) {
        return fetch(Courses.COURSES.NAME, values);
    }
}
