/*
 * This file is generated by jOOQ.
 */
package com.kenvix.studentmanager.orm.tables.daos;


import com.kenvix.studentmanager.orm.tables.Papers;
import com.kenvix.studentmanager.orm.tables.records.PapersRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PapersDao extends DAOImpl<PapersRecord, com.kenvix.studentmanager.orm.tables.pojos.Papers, Long> {

    /**
     * Create a new PapersDao without any configuration
     */
    public PapersDao() {
        super(Papers.PAPERS, com.kenvix.studentmanager.orm.tables.pojos.Papers.class);
    }

    /**
     * Create a new PapersDao with an attached configuration
     */
    public PapersDao(Configuration configuration) {
        super(Papers.PAPERS, com.kenvix.studentmanager.orm.tables.pojos.Papers.class, configuration);
    }

    @Override
    public Long getId(com.kenvix.studentmanager.orm.tables.pojos.Papers object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Papers> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Papers.PAPERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Papers> fetchById(Long... values) {
        return fetch(Papers.PAPERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kenvix.studentmanager.orm.tables.pojos.Papers fetchOneById(Long value) {
        return fetchOne(Papers.PAPERS.ID, value);
    }

    /**
     * Fetch records that have <code>person_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Papers> fetchRangeOfPersonId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Papers.PAPERS.PERSON_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>person_id IN (values)</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Papers> fetchByPersonId(Long... values) {
        return fetch(Papers.PAPERS.PERSON_ID, values);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Papers> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(Papers.PAPERS.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.kenvix.studentmanager.orm.tables.pojos.Papers> fetchByTitle(String... values) {
        return fetch(Papers.PAPERS.TITLE, values);
    }
}
